### ISSUE TITLE
coco上的检测训练代码，方便公布下么？

### ISSUE THREAD

**Issue by zmhik** [taoyang1122/MutualNet#1]
请问是否尝试过基于MobileNet的目标检测训练？

**Comment by taoyang1122** [comment]
@zmhik Yes, I am still working on cleaning up the detection codes. The codes and models will be released afterwards. But the implementation should not be very hard based on some detection frameworks (e.g., mmdetection). You can try MobileNet if you are interested. One thing to note that you should not fix BN and use a large batch size if possible.
