### ISSUE TITLE
detection code

### ISSUE THREAD

**Issue by gbyy422990** [taoyang1122/MutualNet#10]
Hi, Its rly a nice work! Could u pls update the detection code?

**Comment by taoyang1122** [comment]
Hi, thanks for your interest. I may not have the chance to update the detection codes recently, I will try to update it after this summer. The implementation should not be very hard. I did it on MMDetection. Basically you just replace Conv and BN layers (in the backbone network) with the operations defined here. Then just follow the same training scheme as in classification. Hope it helps.

**Comment by gbyy422990** [comment]
@taoyang1122 Thinks for your reply taoyang. I will try to do that with your comments, but I don't know how should I do if I use syncing in my code, could u pls give me some advice？or could u pls update ur syncBN code if u using distributed training.
