### ISSUE TITLE
大佬，请问能够上传一份预训练模型到百度云吗？

### ISSUE THREAD

**Issue by Javacr** [taoyang1122/MutualNet#2]
大佬，我在下载您的预训练模型时，发现是谷歌云链接。俺们村里没法子下载。跪求一份国内可以下载的链接。

**Comment by taoyang1122** [comment]
@Javacr I will try to solve this. Stay tuned.

**Comment by taoyang1122** [comment]
@Javacr Hi, I have added the link to BaiduYun, please have a try.
