### ISSUE TITLE
model(input_list[random.randint(0, 3)])，每一次输入训练的input_list.shape是多大？

### ISSUE THREAD

**Issue by yangzhaojason** [taoyang1122/MutualNet#7]

**Comment by yangzhaojason** [comment]
为什么不是整个batch_size？（256,3,224,224）？

**Comment by taoyang1122** [comment]
Input_list is a list of input batchs of different resolutions.

**Comment by yangzhaojason** [comment]
> Input_list is a list of input batchs of different resolutions.

请问一下shape是多大？

**Comment by taoyang1122** [comment]
@yangzhaojason 
len(input_list) = 4. 
input_list[0].shape = (256, 3, 224, 224); input_list[1].shape = (256, 3, 192, 192)... etc.

**Comment by yangzhaojason** [comment]
> @yangzhaojason
> len(input_list) = 4.
> input_list[0].shape = (256, 3, 224, 224); input_list[1].shape = (256, 3, 192, 192)... etc.

for batch_idx, (input_list, target) in enumerate(loader):
这里 input_list就应该是每个batch_size对应的train_loader了，input_list[0]的shape应该是(3, 224, 224)吧？

**Comment by taoyang1122** [comment]
@yangzhaojason In the train_transform, I create a list of input batch of different resolutions. See this [line](https://github.com/taoyang1122/MutualNet/blob/master/utils/datasets.py#L30).
You can also print out the shape to check.
