### ISSUE TITLE
How to implement dynamic inference on MutualNet

### ISSUE THREAD

**Issue by Liuyang829** [taoyang1122/MutualNet#8]
Thanks for your great work about MutualNet especially your training strategy which inspires me a lot.

However, in test period, you test all these width-resolution configurations on a validation set from 1.0-224 to 0.25-128 and finally choose one best configuration according to all the results. In real time,we don't have time to test all these configurations on every sample, so I think this strategy will waste a lot of time. 

Maybe the best way in test is to make the input dynamicly choose the best width-resolution to output directly. Just like the MSDNet meationed in your paper, the input can dynamicly find the most suitable classifier to output judged by a threshold. 

So how to implement dynamic inference on MutualNet in test period? 
Thanks.

**Comment by taoyang1122** [comment]
@Liuyang829 Hi, in real time, you don't have to test all these configurations on every sample. We test all these configurations to get the best configuration for each constraint (e.g. FLOPs). Then this makes our query table where each FLOPs constraint has their corresponding configuration. In real time, you choose the configurations from the query table based on your FLOPs constraint.

**Comment by Liuyang829** [comment]
I understand the usage of query table, but if you use FLOPs as the reference standard of constraint, maybe we can't know the FLOPs constraint of this device, so sometimes the query table may lacks actual meaning in real time. 
In my opinion, If you can make it dynamic or adaptive in test, it will achieve more efficient usage.

**Comment by taoyang1122** [comment]
You can also use the latency as the reference constraint, then you have the config-latency query table.

**Comment by Liuyang829** [comment]
Thank you very much. When I try to train a model with ImageNet on MobileNetv1 backbone, I find that the Memory-Usage of GPU is always very high, but the volatile GPU-Util is very low, even 0%. I want to know why this situation happened and how to avoid this. Thanks.

**Comment by taoyang1122** [comment]
This maybe caused by the data loader. You can improve the data loader speed by
1. increase the num_workers
2. put data on SSD
